server:
  port:

spring:
  application:
    name: billing-service

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: