server:
  port: 50002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: elbouchouki

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
